services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_TIMEZONE: Europe/London
      DATABASE_URL: sqlite:////app/var/data/app.db
      COMPOSER_CACHE_DIR: /tmp/composer-cache
      SERVER_NAME: :8000
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/app
      - composer_cache:/tmp/composer-cache
      - caddy_data:/data
      - caddy_config:/config
      - sqlite_data:/app/var/data

volumes:
  caddy_config:
  caddy_data:
  composer_cache:
  sqlite_data:
